NON_SLATE_3 <- c("MIA", "JAC", "KCC", "BAL", "GBP", "NOS")
NON_SLATE_4 <- c("NYJ", "DEN", "PHI", "SFO", "ATL", "GBP")
NON_SLATE_5 <- c("TBB", "CHI", "MIN", "SEA", "LAR", "NOS")
NON_SLATE_6 <- c("KCC", "BUF", "LAR", "SFO", "ARI", "DAL")
NON_SLATE_7 <- c("NYG", "PHI", "TBB", "LVR", "CHI", "LAR")
NON_SLATE_8 <- c("ATL", "CAR", "DAL", "PHI", "TBB", "NYG")
NON_SLATE_9 <- c("GBP", "SFO", "NOS", "TBP", "NEP", "NYJ")
NON_SLATE_10 <- c("IND", "TEN", "BAL", "NEP", "MIN", "CHI")
NON_SLATE_11 <- c("ARI", "SEA", "KCC", "LVR", "LAR", "TBB")
NON_SLATE_12 <- c("HOU", "DET", "WAS", "DAL", "BAL", "PIT", "CHI", "GBP", "SEA", "PHI")
NON_SLATE_13 <- c("DAL", "BAL", "DEN", "KCC", "BUF", "SFO")
NON_SLATE_14 <- c("NEP", "LAR", "PIT", "BUF", "BAL", "CLE")
NON_SLATE_15 <- c("LAR", "LVR", "SFO", "DAL", "PIT", "CIN")
NON_SLATE_16 <- c("MIN", "NOS", "TEN", "GBP", "BUF", "NEP")