---
title: "About"
output: 
  html_document:
    css: shiny_app/www/styles.css
---

An optimal lineup generated through linear programming is provided for each of the three main DFS platforms (Draftkings, Fanduel, Yahoo). Projections and salaries are continously updated througout the week to provide up to date information needed. If you wish to include a player not in the gnerated lineup, they can be selected from the selection of players available on each platform. Similarly, palyers can be excluded from optimization. 

## Projections and salaries

Player projections and salaries are sourced from [numberFire](https://www.numberfire.com/). These projections are specific to each platform (Draftkings, Fanduel, and Yahoo) and are continously updated throughout the week. 

## Optimization process

Using the sourced projections and salaries, the DFS Optimization App will optimally allocate the budget on each platform to maximize the amount of points projected. The process behind this application was heavily based on previous work done by [Troy Hernandez](https://troyhernandez.com/2016/01/06/optimizing-fanduel-in-r/). 

As mentioned by Troy, a downside of this approach is that the NFL, fantasy football, and player scoring are volatile and player projections may not end up matching player performance after the game. 

To address this, our application allows for inclusion or exclusion of players. By including or excluding players from the optimization process, player projections you feel may be too high or too low can be taken into account. For each inclusion and exclusion, the paramaters of the linear programming algorithm update to take into account remaining lineup needed, remaining budget, and players to choose from.

## Points until optimal measure

Using the sourced projections and salaires, the DFS Optimization App also provides information on how close to optimal players are. Every player that is not in the default optimal lineup is given extra points up to the point at which they become optimal. This difference between projected points and points needed until optimal gives insight into how valuable each player is when taking into account the projections and salaries of all potential players.

## Disclaimer

This application is simply here to provide information about sports picks for entertainment purposes. Generated lineups or picks are not guaranteed to provide monetary gain in any betting or DFS type contests. 
