  
name: script

# on:
#  schedule:
#    - cron:  '*/30 * * * *'
on: 
  push:
    branches:
      - data_2021_start

jobs:

  script:
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        
      - name: Install packages
        run: |
          R -e 'install.packages("data.table")'
          R -e 'install.packages("xml2")'
          R -e 'install.packages("rvest")'
          
      - name: run_data
        run: Rscript data/run_data.R
      
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "Github Actions: Data Scrape"
          git push origin data_2021_start 
